Assignment 2 - Code on R8, Detailed Test Plan, Code Reorganization
atangent/chad-CI-python pull request #13
Opened 2020-11-07 15:14 UTC by Chumingsun

2020-11-07 20:24 UTC, SethDamiani commented
Few quick notes:

- Your tests fail due to multiple test files sharing the same name, which pytest does not allow.
- The title of your 404 page is 'Profile', which should probably be changed to something like 'Page not found'
- For consistency, we should format our Detailed Test Plan in markdown instead of Word/PDF

After those are fixed I think we'll be good to merge.

2020-11-08 16:37 UTC, SethDamiani approved these changes

2020-11-08 17:09 UTC, atangent requested changes
I think parts of the code in `frontend.py` could be modularized

2020-11-08 17:09 UTC, atangent commented on qa327/frontend.py
> +    elif (len(email) < 1 or not re.match(r"^[A-Za-z0-9\.\+_-]+@[A-Za-z0-9\._-]+\.[a-zA-Z]*$", email)):
This is a good line of code to validate the email format. 

However, I'm seeing this twice in this file. I think this line could be modularized into a function that returns `True` if the email is valid or `False` if the email is not valid. This ensures we follow DRY principles and makes the code cleaner too.

Then you could call it here like:
```
if not function:
    # error message and/or re-render login page 
 ```
which you can do again the second time you need to check email format.

2020-11-08 17:09 UTC, atangent commented on qa327/frontend.py
> +    if (len(email) < 1 or not re.match(r"^[A-Za-z0-9\.\+_-]+@[A-Za-z0-9\._-]+\.[a-zA-Z]*$", email)):
This is where you repeat yourself

2020-11-09 03:03 UTC, atangent approved these changes
Looks good to me

2020-11-09 03:04 UTC, merged