Validation for account registration
atangent/chad-CI-python pull request #16
Opened 2020-11-08 22:10 UTC by Kymed

2020-11-08 23:00 UTC, atangent reviewed
Some code could be modularized to improve code readability and maintainability

2020-11-08 23:00 UTC, atangent commented on qa327/frontend.py
> +EMAIL_REGEX = re.compile(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)")
i like this. nice.

2020-11-08 23:00 UTC, atangent commented on qa327/frontend.py
> +        error_message = "Name format is incorrect"
These could be modularized into a function, to separate the logic from the `if` condition

It would make the code a lot cleaner!

2020-11-08 23:00 UTC, atangent commented on qa327/frontend.py
> +        error_message = "Email format is incorrect"
I left a comment in @Chumingsun 's PR, basically that he could modularize the email format checking function [here](https://github.com/atangent/chad-CI-python/pull/13/files?file-filters%5B%5D=.html&file-filters%5B%5D=.py#r519451544)

Since you're working on the same function in the same file, it might be helpful to look over his code and make sure both his and your code won't conflict each other

I still recommend modularizing the email checking here. If you do it, comment on his PR and say you did it and he can just call the function in his code

2020-11-08 23:00 UTC, atangent commented on qa327/frontend.py
> +        error_message = "Name format is incorrect"
I also wrote a password format checker in my PR [here](https://github.com/atangent/chad-CI-python/pull/14) in `frontend.py` under the function `check_password_format`

2020-11-08 23:42 UTC, SethDamiani requested changes
One quick optimization!

2020-11-08 23:42 UTC, SethDamiani commented on qa327/frontend.py
> +    elif len(name) < 2 or len(name) >= 20 or (any(not x.isalnum() for x in name)) or name[0] == ' ' or name[-1] == ' ':
I would avoid calling `len` on `name` more than once - maybe store the length in a variable before the `if` statement.

2020-11-09 03:47 UTC, SethDamiani approved these changes

2020-11-09 03:47 UTC, merged